config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "staticpages#index"
  resources :staticpages, only: [:show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
  end
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' },
    { id: 8, name: '70代' },
    { id: 9, name: '80代' },
    { id: 10, name: '90代' },
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  with_options presence: true do
    validates :visual_reading
    validates :question
    validates :answer
  end

  belongs_to :user
  belongs_to :post

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '男性' },
    { id: 3, name: '女性' },
    { id: 4, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/post.rb
class Post < ApplicationRecord

  with_options presence: true do
    validates :visual_reading
    validates :question
    validates :answer
    validates :image
  end

  belongs_to :user
  has_one_attached :image
  has_many :comments
end

app/models/profession.rb
class Profession < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '自営業' },
    { id: 3, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :gender_id
    validates :age_id
    validates :profession_id
  end

  has_many :posts
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :age
  belongs_to :profession
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_pemitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_pemitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender_id, :age_id, :profession_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments.new(comment_params)
    if @comments.save
       redirect_to post_path(@post.id)
    else
      # @post = @comment.post
      # @comments = @post.comments
      render "posts/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:visual_reading, :question, :answer).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :visual_reading, :question, :answer).merge(user_id: current_user.id)
  end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end

  def show
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://unpkg.com/scrollreveal"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
  </head>

  <body>
    <%= yield %>
     <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
     <script>
      var swiper = new Swiper('.swiper-container', {
        loop: true,
        speed: 2000,
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
        pagination: {
          el: '.swiper-pagination',
          type: 'bullets',
          clickable: true
        }
      });
    </script>
  </body>
</html>

app/views/layouts/index.html.erb
hello word

app/views/posts/edit.html.erb
<div class="contemporary-content">
<div class="header">
  <%= link_to image_tag("home.png", size: '23x23', class: "home"), root_path %>
  <%= link_to image_tag("contemporary.png", size: '23x23', class: "contemporary"), posts_path %>
</div>

 <%= form_with(model: @post, local: true) do |f| %>
     <%= image_tag @post.image, class:"post-img" %>

    <div class="field">
      <%= f.label :visual_reading, "視覚で感じること" %><br />
      <%= f.text_area :visual_reading, class: :form__text %>
    </div>

    <div class="field">
      <%= f.label :question, "自ら作った問い" %><br />
      <%= f.text_area :question, class: :form__text %>
    </div>

    <div class="field">
      <%= f.label :answer, "自分なりの答え" %><br />
      <%= f.text_area :answer, class: :form__text %>
    </div>

    <div class="actions">
      <%= f.submit "投稿", class: :form__btn  %>
    </div>
  <% end %>
 </div>

app/views/posts/index.html.erb
<div class='list-page'>
    <div class="page-icon">
      <%= link_to image_tag("home.png", size: '23x23', class: "home"), root_path %>
    </div>
  <div class='list-page-header'>
    <div class='header-title'>コンテンポラリー</div>
  </div>
  <div class='list-image'>
    <% @posts.each do |post| %>
      <%=link_to image_tag(post.image, class: "post_imag"), post_path(post.id) %>
    <% end %>
  </div>
  <script>ScrollReveal().reveal('.list-page', { 
                 duration: 1600,
                 reset: true   
         });</script>
</div>

app/views/posts/new.html.erb
<div class='post-page'>
 <div class='post-input'>
  <%= form_with(model: @post, local: true) do |f| %>
    <div class="field">
      <%= f.label :image, "作品画像" %><br />
      <%= f.file_field :image, id:"post-image" %>
      <div id="preview"></div>
    </div>

    <div class="field">
      <%= f.label :visual_reading, "視覚で感じること" %><br />
      <%= f.text_area :visual_reading, class: :form__text %>
    </div>

    <div class="field">
      <%= f.label :question, "自ら作った問い" %><br />
      <%= f.text_area :question, class: :form__text %>
    </div>

    <div class="field">
      <%= f.label :answer, "自分なりの答え" %><br />
      <%= f.text_area :answer, class: :form__text %>
    </div>

    <div class="actions">
      <%= f.submit "投稿", class: :form__btn  %>
    </div>
  <% end %>
 </div>
 <script>ScrollReveal().reveal('.post-page', { 
                 duration: 1600,
                 reset: true   
         });</script>
</div>

app/views/posts/show.html.erb
<div class="contemporary-content">
<div class="header">
  <%= link_to image_tag("home.png", size: '23x23', class: "home"), root_path %>
  <%= link_to image_tag("contemporary.png", size: '23x23', class: "contemporary"), posts_path %>
</div>

 <div class="post-main">
      <%= image_tag @post.image, class:"post-img" %>
    <div class="post-visual_reading">
      <%= @post.visual_reading %>
    </div>
    <div class="post-question">
      <%= @post.question %>
    </div>   
    <div class="post-answer">
      <%= @post.answer %>
    </div> 
    <div class="post-nickname">
      <%= @post.user.nickname %>  
    </div>
 </div>


  <% if user_signed_in? %>
      <% if current_user == @post.user %>
        <%= link_to image_tag("edit.png", size: '23×23', class: "post-edit"), edit_post_path(@post.id), method: :get %>
        <%= link_to image_tag("destroy.png", size: '23×23', class: "post-destroy"), post_path(@post.id), method: :delete %>
      <% end %>
    <% end %>

<% if user_signed_in? %>
  <% unless current_user == @post.user %>
    <div class="post-comment">
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <div class="field">
          <%= f.label :visual_reading, "視覚で感じること" %><br />
          <%= f.text_area :visual_reading, class: :form_text %><br />

          <%= f.label :question, "自ら作った問い" %><br />
          <%= f.text_area :question, class: :form_text %><br />
          
          <%= f.label :answer, "自分なりの答え" %><br />
          <%= f.text_area :answer, class: :form_text %>
        </div>
        
        <div class="actions">
          <%= f.submit "投稿", class: :form_btn %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="other-comments">
  <h2>other think</h2>
  <% @comments.each do |comment| %>
    <p>
    <strong><%= comment.user.nickname %></strong>
    <p><%= comment.visual_reading %></p>
    <p><%= comment.question%></p>
    <p><%= comment.answer %></p>
    </p>
  <% end %>
</div>
<script>ScrollReveal().reveal('.contemporary-content', { 
                 duration: 1600,
                 reset: true   
         });</script>
</div>

app/views/staticpages/index.html.erb
<div class="start">
    <p>Art think</p>
</div>
<div class='main'>
    <div class='main-visual'>
      <%= image_tag "art-main01.png", class:"main-image" %>
        <div class='main-title'>
         <h2>"アート思考で</h2>
         <h3>クリエイティブに"</h3>
        </div>
      <div class='top-page-header'>
       <div class='nav'>
        <ul class='lists'>
          <% if user_signed_in? %>
            <li><%= link_to current_user.nickname, staticpage_path(current_user.posts), class: "user-nickname" %></li> 
            <li><%= link_to image_tag("post.png", class: "post"), new_post_path %></li>
            <li><%= link_to image_tag("logout.png", size: '23x23', class: "logout"), destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to image_tag("user_icon.png", size: '23x23', class: "sign-up"), new_user_registration_path %></li>
            <li><%= link_to image_tag("login.png", size: '23x23', class: "login"), new_user_session_path %></li>
          <% end %>  
        </ul>
      </div>
    </div>
  </div>
    
  <div class='second-visual'>
    <%= image_tag "second-visual-image.png", class:"second-image" %>
      <div class='artthinking'>
        <h3>「正解を見つける力」から</h3>
        <h2>「答えを作る力」へ</h2>
        <script>ScrollReveal().reveal('.artthinking', { 
                 duration: 1600,
                 reset: true   
         });</script>
      </div>
      
      <div class="artthinking-description">
        <h3 class="artthinking-title">アート思考とは!?<p>"自分だけの答えを作ること"</p></h3>
         <div class="artthinking-commentary">
            <h4>例えば数学は、太陽のように明確で唯一の答えが存在しています。</h4>
            <h4>「1+1＝2」が正しいことは、すでにはっきりしています。</h4>
            <h4>数学が太陽とするならば、アートは雲です。</h4>
            <h4>太陽はいつもそこにありますが、雲は形を変えています。</h4>
            <h4>アーティストが導き出す自分なりの答えは、そもそも形が定まっておらず、</h4>
            <h4>見る人や時が異なれば、いかようにも変化します。</h4>
            <h4>子どもは空に浮かぶ雲を眺めながら、「ゾウがいる」「巨人にも見える」</h4>
            <h4>「やっぱりトリだ」などと「自分なりの答え」を作ってます。</h4>
            <h4>アート思考の目的は、この「自分なりの答え（＝雲）」を作る思考力を育むことです。</h4>
         </div>
         <script>ScrollReveal().reveal('.artthinking-description', { 
                 duration: 1600,
                 reset: true   
         });</script>
      </div>
    </div>
     
      <div class="swiper-container">
        <h3 class="app-method">アート思考のメソッド</h3> 
          <div class="swiper-wrapper">
            <div class="swiper-slide"><h2>"視覚で感じたこと"</h2>
              <h5>こちちらはピカソの有名な作品です。</h5>
              <h5>この作品を見て何をかんじるでしょうか?</h5>
              <h5>なんか悲しそう、色がカラフルだな、よくわからない、</h5>
              <h5>まずは自分が感じたことを素直に書いてみましょう</h5>
            </div>
            <div class="swiper-slide"><h2>"自ら問いを作る"</h2>
              <h5>先程の作品であれえば、なにか悲しい出来事があったのかな?</h5>
              <h5>沢山の色が、今の自分にいろんな事が起きていて、目まぐるしいのかな?</h5>
              <h5>いや、それとも嬉し泣きなんじゃないかな?</h5>
              <h5>いろんな角度から、自ら問いを作り出してみましょう!</h5>
            </div>
            <div class="swiper-slide"><h2>"自なりの答え"</h2>
              <h5>先程の作品で自分が出した答えは、</h5>
              <h5>「自分に関わるもの全てに感謝を表している絵」です。</h5>
              <h5>このように、自分なりの答えをつくることが、”アート思考”です!</h5>
              <h5>アート思考をしていくことで、どんどん自分の発想も</h5>
              <h5>クリエイティブになっていきます!</h5>
              <h5>自分らしく、自由に、アート思考を楽しみましょう！！</h5>
            </div>
        </div>
              <div class="swiper-button-next"></div>
              <div class="swiper-button-prev"></div>
              <div class="swiper-pagination"></div>
              <script>ScrollReveal().reveal('.swiper-container', { 
                 duration: 1600,
                 reset: true   
         });</script>
    </div>

   <div class="contemporary">
     <div class="list"><%= link_to 'コンテンポラリー', posts_path %></div>
     <div class="contemporary-image">
      <%= image_tag "img1.jpg", class:"work" %>
      <%= image_tag "img2.jpg", class:"work" %>
      <%= image_tag "img3.jpg", class:"work" %>
      <%= image_tag "img4.jpg", class:"work" %>
      <script>ScrollReveal().reveal('.contemporary', { 
                 duration: 1600,
                 reset: true   
         });</script>
   </div>

    

</div> 

app/views/staticpages/show.html.erb
<div class='list-page'>
    <div class="page-icon">
      <%= link_to image_tag("home.png", size: '23x23', class: "home"), root_path %>
      <%= link_to image_tag("contemporary.png", size: '23x23', class: "contemporary"), posts_path %>
    </div>
  <div class='list-page-header'>
    <div class='header-title'>My page</div>
  </div>
  <div class='list-image'>
    <% @posts.each do |post| %>
      <%= link_to image_tag(post.image, class: "post_imag"), post_path(post.id) %>
    <% end %>
  </div>
  <script>ScrollReveal().reveal('.list-page', { 
                 duration: 1600,
                 reset: true   
         });</script>
</div>